name: saucectl xcuitest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build iOS App for Simulator
        run: |
          xcodebuild -project Features.xcodeproj \
                     -scheme Features \
                     -sdk iphonesimulator \
                     -arch arm64 -arch x86_64 \
                     -configuration Debug \
                     -derivedDataPath $PWD/build \
                     clean build

      - name: Compress Features.app bundle
        run: |
          cd build/Build/Products/Debug-iphonesimulator
          zip -r Features.app.zip Features.app

      - name: Upload Features.app to Sauce Labs
        run: |
          curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
                   --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
                   --data-binary @"$PWD/build/Build/Products/Debug-iphonesimulator/Features.app.zip" \
                   --form 'payload=@"g16K4P8IX/Features.app.zip"' \
                   --form 'name="Features.app.zip"' \
                   --form 'description="Features"'

      - name: Compress FeaturesUITests-Runner.app bundle
        run: zip -r FeaturesUITests-Runner.app.zip FeaturesUITests-Runner.app

      - name: Upload FeaturesUITests-Runner.app to Sauce Labs
        run: |
          curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
                   --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
                   --data-binary @"$PWD/build/Build/Products/Debug-iphonesimulator/FeaturesUITests-Runner.app.zip" \
                   --form 'payload=@"g16K4P8IX/FeaturesUITests-Runner.app.zip"' \
                   --form 'name="FeaturesUITests-Runner.app.zip"' \
                   --form 'description="FeaturesUITests-Runner"'

      - name: Run saucectl
        uses: saucelabs/saucectl-run-action@v4
