name: saucectl xcuitest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build iOS App for Simulator
        run: |
          xcodebuild -project Features.xcodeproj \
           -scheme Features \
           -sdk iphonesimulator \
           -configuration Debug \
           -derivedDataPath $PWD/build \
           -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
           clean build-for-testing

      - name: Compress Features.app & FeaturesUITests-Runner.app bundles
        run: |
          cd build/Build/Products/Debug-iphonesimulator
          zip -r Features.app.zip Features.app
          zip -r FeaturesUITests-Runner.app.zip FeaturesUITests-Runner.app
          ls -al

      - name: Upload Features.app to Sauce Labs
        run: |
          curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" \
          --location \
          --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
          --form payload=@g16K4P8IX/$PWD/build/Build/Products/Debug-iphonesimulator/Features.app.zip

      - name: Upload FeaturesUITests-Runner.app to Sauce Labs
        run: |
          curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" \
          --location \
          --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
          --form payload=@g16K4P8IX/$PWD/build/Build/Products/Debug-iphonesimulator/FeaturesUITests-Runner.app.zip

      - name: Run saucectl
        uses: saucelabs/saucectl-run-action@v4
