name: saucectl xcuitest

on:
  pull_request:
  push:
    paths:
      - ".saucectl"
    branches:
      - main

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run saucectl
        uses: saucelabs/saucectl-run-action@v4
        with:
          working-directory: .saucectl 
